Put error-detecting code into the atomic helper scripts.

diff --git a/1flactovorbis b/1flactovorbis
--- a/1flactovorbis
+++ b/1flactovorbis
@@ -18,3 +18,9 @@ else  # Otherwise, print usage and exit with error
   echo "See the abcde manpage for more information." >&2
   exit 1
 fi
+
+if [[ $? -ne 0 ]]; then
+  echo "abcde exited with an error while creating transcodes of the 1-file FLAC." >&2
+  echo "See the abcde manpage for more information." >&2
+  exit $?
+fi
diff --git a/cdto1flac b/cdto1flac
--- a/cdto1flac
+++ b/cdto1flac
@@ -16,4 +16,10 @@ shift
 
 abcde -1 -d $cd_device -o flac -a default,cue
 
+if [[ $? -ne 0 ]]; then
+  echo "abcde exited with an error while creating a 1-file FLAC of the CD." >&2
+  echo "See the abcde manpage for more information." >&2
+  exit $?
+fi
+
 eject $cd_device &
