Make all the scripts check for required executables & improve error messaging.

diff --git a/1flactoogg b/1flactoogg
--- a/1flactoogg
+++ b/1flactoogg
@@ -4,11 +4,17 @@
 # Debugging
 set -x
 
+# Check for abcde before execution
+if ! hash "abcde" >/dev/null 2>&1; then
+  echo "Command not found in PATH: abcde" >&2
+  exit 1
+fi
+
 # If command-line argument is a filename that ends in ".flac", process it
 if [[ $1 =~ .flac$ ]]; then
   abcde -d "$1" -N -o ogg
 else  # Otherwise, print usage and exit with error  
-  echo "A FLAC file, especially with an embedded cuesheet, should be specified on the command-line."
-  echo "See the abcde manpage for more information."
+  echo "A FLAC file, especially with an embedded cuesheet, should be specified on the command-line." >&2
+  echo "See the abcde manpage for more information." >&2
   exit 1
 fi
diff --git a/cdto1flac b/cdto1flac
--- a/cdto1flac
+++ b/cdto1flac
@@ -4,6 +4,12 @@
 # Debugging
 set -x
 
+# Check for abcde before execution
+if ! hash "abcde" >/dev/null 2>&1; then
+  echo "Command not found in PATH: abcde" >&2
+  exit 1
+fi
+
 # Set device as the passed parameter, or a sensible default
 cd_device=${1:-/dev/sr0}
 shift
diff --git a/digitize-cd b/digitize-cd
--- a/digitize-cd
+++ b/digitize-cd
@@ -27,6 +27,20 @@ set -x
 ################################
 ####### CHECK CONDITIONS #######
 ################################
+### Check for necessary commands
+my_needed_commands="find /bin/rm mktemp pwd zenity"
+missing_counter=0
+for needed_command in $my_needed_commands; do
+  if ! hash "$needed_command" >/dev/null 2>&1; then
+    printf "Command not found in PATH: %s\n" "$needed_command" >&2
+    ((missing_counter++))
+  fi
+done
+if ((missing_counter > 0)); then
+  printf "Minimum %d commands are missing in PATH, aborting\n" "$missing_counter" >&2
+  exit 1
+fi
+
 ### Check for enough HDD space.  ??43GB = 18GB + 25GB buffer
 
 ##############################
@@ -74,6 +88,7 @@ transcodedir=$(find * -maxdepth 0 -type d)
 ### Check for filename collision
 # Rip collision
 if [[ -f "$nasrip/$flacfile" ]]; then
+  echo "$nasrip/$flacfile already exists!  Exiting." >&2
   zenity --error --text="$nasrip/$flacfile already exists!  Exiting."
   exit 1
 fi
diff --git a/digitize-dvd b/digitize-dvd
--- a/digitize-dvd
+++ b/digitize-dvd
@@ -12,8 +12,8 @@
 #
 #      PROJECT: Media Collection (media-archive)
 #      OPTIONS: 
-# REQUIREMENTS: asdf
-# PACKAGES REQ: asdf
+# REQUIREMENTS: dvdbackup
+# PACKAGES REQ: dvdbackup
 #         BUGS: Probably dozens.
 #        NOTES: ---
 #       AUTHOR: KlfJoat
@@ -25,6 +25,20 @@
 ################################
 ####### CHECK CONDITIONS #######
 ################################
+### Check for necessary commands
+my_needed_commands="find basename /bin/rm mktemp pwd zenity"
+missing_counter=0
+for needed_command in $my_needed_commands; do
+  if ! hash "$needed_command" >/dev/null 2>&1; then
+    printf "Command not found in PATH: %s\n" "$needed_command" >&2
+    ((missing_counter++))
+  fi
+done
+if ((missing_counter > 0)); then
+  printf "Minimum %d commands are missing in PATH, aborting\n" "$missing_counter" >&2
+  exit 1
+fi
+
 ### Check for enough HDD space.  43GB = 18GB + 25GB buffer
 ### Check if DVD is a movie or TV show
 
diff --git a/dvdtoiso b/dvdtoiso
--- a/dvdtoiso
+++ b/dvdtoiso
@@ -1,7 +1,23 @@
 #!/bin/bash
+#
+# Requirements: dvdbackup
 
 # Debugging
 set -x
+
+# Check for this script's requirements & exit with error if they are not found.
+my_needed_commands="dvdbackup mkisofs zenity eject notify-send"
+missing_counter=0
+for needed_command in $my_needed_commands; do
+  if ! hash "$needed_command" >/dev/null 2>&1; then
+    printf "Command not found in PATH: %s\n" "$needed_command" >&2
+    ((missing_counter++))
+  fi
+done
+if ((missing_counter > 0)); then
+  printf "Minimum %d commands are missing in PATH, aborting\n" "$missing_counter" >&2
+  exit 1
+fi
 
 # Set device as the passed parameter, or a sensible default
 dvd_device=${1:-/dev/sr0}
@@ -60,7 +76,8 @@ mkisofs -A "$title" -dvd-video -udf -quiet -output "$isoTitle" "$title"
 # If error during mkisofs, complain and exit
 if [ $? -ne 0 ] ; then
   curdir=$(pwd)
-  zenity --error --text="ERROR RUNNING mkisofs/genisoimage on $curdir/$title/ to make $curdir/$isoTitle"
+  echo "ERROR running mkisofs/genisoimage on $curdir/$title/ to make $curdir/$isoTitle" >&2
+  zenity --error --text="ERROR running mkisofs/genisoimage on $curdir/$title/ to make $curdir/$isoTitle"
   exit $? 
 fi
 
