Update the first call to abcde to keep the directory between calls. Add error checking for the abcde calls.

diff --git a/digitize-cd b/digitize-cd
--- a/digitize-cd
+++ b/digitize-cd
@@ -81,7 +81,14 @@ trap clean_up 0 1 2 3 15
 ###########################################
 ####### DUAL - RIP AND GET CD INFO #######
 ###########################################
-abcde -1 -o flac -a default,cue
+abcde -1 -e -k -o flac -a default,cue
+
+if [[ $? -ne 0 ]]; then
+  echo "abcde exited with an error while creating a 1-file FLAC of the CD." >&2
+  echo "See the abcde manpage for more information." >&2
+  exit 1
+fi
+
 
 ### Figure out FLAC filename (should be the only one in our temp directory)
 flacfile=$(find *.flac)
@@ -95,6 +102,12 @@ flacfile=$(find *.flac)
 ####### TRANSCODE #######
 #########################
 abcde -d "$flacfile" -N -o ogg
+
+if [[ $? -ne 0 ]]; then
+  echo "abcde exited with an error while creating transcodes of the 1-file FLAC." >&2
+  echo "See the abcde manpage for more information." >&2
+  exit 1
+fi
 
 ### Get directory of filename minus dirs and minus ext (use for transcode filename)
 transcodedir=$(find * -maxdepth 0 -type d)
